
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package gt.edu.usac.ingenieria.analyzer.json;

import java.util.stream.Collectors;
import java_cup.runtime.*;
import java.util.Arrays;
import java.util.ArrayList;
import gt.edu.usac.ingenieria.analyzer.errors.SynError;
import gt.edu.usac.ingenieria.lang.json.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class JsonParser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return SYM.class;
}

  /** Default constructor. */
  @Deprecated
  public JsonParser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public JsonParser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public JsonParser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\015\000\002\002\004\000\002\002\003\000\002\003" +
    "\004\000\002\003\005\000\002\004\004\000\002\004\003" +
    "\000\002\005\006\000\002\005\005\000\002\006\003\000" +
    "\002\006\003\000\002\006\003\000\002\006\004\000\002" +
    "\006\004" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\024\000\004\004\006\001\002\000\004\002\000\001" +
    "\002\000\004\002\026\001\002\000\006\005\007\010\012" +
    "\001\002\000\004\002\uffff\001\002\000\006\005\ufffc\010" +
    "\ufffc\001\002\000\006\005\024\010\012\001\002\000\004" +
    "\006\013\001\002\000\012\010\016\011\015\012\017\013" +
    "\014\001\002\000\006\011\022\012\023\001\002\000\010" +
    "\005\ufff7\007\ufff7\010\ufff7\001\002\000\010\005\ufff9\007" +
    "\ufff9\010\ufff9\001\002\000\010\005\ufff8\007\ufff8\010\ufff8" +
    "\001\002\000\010\005\ufffa\007\021\010\ufffa\001\002\000" +
    "\006\005\ufffb\010\ufffb\001\002\000\010\005\ufff6\007\ufff6" +
    "\010\ufff6\001\002\000\010\005\ufff5\007\ufff5\010\ufff5\001" +
    "\002\000\004\002\ufffe\001\002\000\006\005\ufffd\010\ufffd" +
    "\001\002\000\004\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\024\000\006\002\004\003\003\001\001\000\002\001" +
    "\001\000\002\001\001\000\006\004\010\005\007\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\005\024\001" +
    "\001\000\002\001\001\000\004\006\017\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$JsonParser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$JsonParser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$JsonParser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    public ArrayList<SynError> errors = new ArrayList<>();
    public ArrayList<KeyVal> content = new ArrayList<>();
    public void syntax_error(Symbol s){
        errors.add(new SynError(s.left, s.right, s.value, SYM.terminalNames[s.sym]));
    }

    public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception{
        errors.add(new SynError("Syntax error, impossible to recover"));
    }
    public ArrayList<SynError> getErrors() {
        return errors;
        //return errors.stream().map(Object::toString).collect(Collectors.joining("\n-> "));
    }
    public boolean isSuccessExecution() {
        return !(errors.size() > 0);
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$JsonParser$actions {
  private final JsonParser parser;

  /** Constructor */
  CUP$JsonParser$actions(JsonParser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$JsonParser$do_action_part00000000(
    int                        CUP$JsonParser$act_num,
    java_cup.runtime.lr_parser CUP$JsonParser$parser,
    java.util.Stack            CUP$JsonParser$stack,
    int                        CUP$JsonParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$JsonParser$result;

      /* select the action based on the action number */
      switch (CUP$JsonParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= Init EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$JsonParser$stack.elementAt(CUP$JsonParser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$JsonParser$stack.elementAt(CUP$JsonParser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$JsonParser$stack.elementAt(CUP$JsonParser$top-1)).value;
		RESULT = start_val;
              CUP$JsonParser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$JsonParser$stack.elementAt(CUP$JsonParser$top-1)), ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$JsonParser$parser.done_parsing();
          return CUP$JsonParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // Init ::= Object 
            {
              Object RESULT =null;

              CUP$JsonParser$result = parser.getSymbolFactory().newSymbol("Init",0, ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()), RESULT);
            }
          return CUP$JsonParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // Object ::= TK_LBRC TK_RBRC 
            {
              Object RESULT =null;

              CUP$JsonParser$result = parser.getSymbolFactory().newSymbol("Object",1, ((java_cup.runtime.Symbol)CUP$JsonParser$stack.elementAt(CUP$JsonParser$top-1)), ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()), RESULT);
            }
          return CUP$JsonParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // Object ::= TK_LBRC Contents TK_RBRC 
            {
              Object RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$JsonParser$stack.elementAt(CUP$JsonParser$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$JsonParser$stack.elementAt(CUP$JsonParser$top-1)).right;
		ArrayList<KeyVal> c = (ArrayList<KeyVal>)((java_cup.runtime.Symbol) CUP$JsonParser$stack.elementAt(CUP$JsonParser$top-1)).value;
		content = c;
              CUP$JsonParser$result = parser.getSymbolFactory().newSymbol("Object",1, ((java_cup.runtime.Symbol)CUP$JsonParser$stack.elementAt(CUP$JsonParser$top-2)), ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()), RESULT);
            }
          return CUP$JsonParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // Contents ::= Contents Content 
            {
              ArrayList<KeyVal> RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$JsonParser$stack.elementAt(CUP$JsonParser$top-1)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$JsonParser$stack.elementAt(CUP$JsonParser$top-1)).right;
		ArrayList<KeyVal> l = (ArrayList<KeyVal>)((java_cup.runtime.Symbol) CUP$JsonParser$stack.elementAt(CUP$JsonParser$top-1)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()).right;
		KeyVal c = (KeyVal)((java_cup.runtime.Symbol) CUP$JsonParser$stack.peek()).value;
		RESULT = l; RESULT.add(c);
              CUP$JsonParser$result = parser.getSymbolFactory().newSymbol("Contents",2, ((java_cup.runtime.Symbol)CUP$JsonParser$stack.elementAt(CUP$JsonParser$top-1)), ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()), RESULT);
            }
          return CUP$JsonParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // Contents ::= Content 
            {
              ArrayList<KeyVal> RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()).right;
		KeyVal c = (KeyVal)((java_cup.runtime.Symbol) CUP$JsonParser$stack.peek()).value;
		RESULT = new ArrayList<>(Arrays.asList(c));
              CUP$JsonParser$result = parser.getSymbolFactory().newSymbol("Contents",2, ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()), RESULT);
            }
          return CUP$JsonParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // Content ::= TK_STRING TK_COLON ValueType TK_COMA 
            {
              KeyVal RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$JsonParser$stack.elementAt(CUP$JsonParser$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$JsonParser$stack.elementAt(CUP$JsonParser$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$JsonParser$stack.elementAt(CUP$JsonParser$top-3)).value;
		int vleft = ((java_cup.runtime.Symbol)CUP$JsonParser$stack.elementAt(CUP$JsonParser$top-1)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$JsonParser$stack.elementAt(CUP$JsonParser$top-1)).right;
		Value v = (Value)((java_cup.runtime.Symbol) CUP$JsonParser$stack.elementAt(CUP$JsonParser$top-1)).value;
		RESULT = new KeyVal(idleft, idright, id, v);
              CUP$JsonParser$result = parser.getSymbolFactory().newSymbol("Content",3, ((java_cup.runtime.Symbol)CUP$JsonParser$stack.elementAt(CUP$JsonParser$top-3)), ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()), RESULT);
            }
          return CUP$JsonParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // Content ::= TK_STRING TK_COLON ValueType 
            {
              KeyVal RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$JsonParser$stack.elementAt(CUP$JsonParser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$JsonParser$stack.elementAt(CUP$JsonParser$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$JsonParser$stack.elementAt(CUP$JsonParser$top-2)).value;
		int vleft = ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()).right;
		Value v = (Value)((java_cup.runtime.Symbol) CUP$JsonParser$stack.peek()).value;
		RESULT = new KeyVal(idleft, idright, id, v);
              CUP$JsonParser$result = parser.getSymbolFactory().newSymbol("Content",3, ((java_cup.runtime.Symbol)CUP$JsonParser$stack.elementAt(CUP$JsonParser$top-2)), ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()), RESULT);
            }
          return CUP$JsonParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // ValueType ::= TK_STRING 
            {
              Value RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()).right;
		String v = (String)((java_cup.runtime.Symbol) CUP$JsonParser$stack.peek()).value;
		RESULT = new Value(vleft, vright, v, Type.STRING);
              CUP$JsonParser$result = parser.getSymbolFactory().newSymbol("ValueType",4, ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()), RESULT);
            }
          return CUP$JsonParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // ValueType ::= TK_DOUBLE 
            {
              Value RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()).right;
		String v = (String)((java_cup.runtime.Symbol) CUP$JsonParser$stack.peek()).value;
		RESULT = new Value(vleft, vright, v, Type.DOUBLE);
              CUP$JsonParser$result = parser.getSymbolFactory().newSymbol("ValueType",4, ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()), RESULT);
            }
          return CUP$JsonParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // ValueType ::= TK_INT 
            {
              Value RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()).right;
		String v = (String)((java_cup.runtime.Symbol) CUP$JsonParser$stack.peek()).value;
		RESULT = new Value(vleft, vright, v, Type.INT);
              CUP$JsonParser$result = parser.getSymbolFactory().newSymbol("ValueType",4, ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()), RESULT);
            }
          return CUP$JsonParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // ValueType ::= TK_MINUS TK_INT 
            {
              Value RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$JsonParser$stack.elementAt(CUP$JsonParser$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$JsonParser$stack.elementAt(CUP$JsonParser$top-1)).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$JsonParser$stack.elementAt(CUP$JsonParser$top-1)).value;
		int vleft = ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()).right;
		String v = (String)((java_cup.runtime.Symbol) CUP$JsonParser$stack.peek()).value;
		RESULT = new Value(sleft, sright, s + v, Type.INT);
              CUP$JsonParser$result = parser.getSymbolFactory().newSymbol("ValueType",4, ((java_cup.runtime.Symbol)CUP$JsonParser$stack.elementAt(CUP$JsonParser$top-1)), ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()), RESULT);
            }
          return CUP$JsonParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // ValueType ::= TK_MINUS TK_DOUBLE 
            {
              Value RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$JsonParser$stack.elementAt(CUP$JsonParser$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$JsonParser$stack.elementAt(CUP$JsonParser$top-1)).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$JsonParser$stack.elementAt(CUP$JsonParser$top-1)).value;
		int vleft = ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()).right;
		String v = (String)((java_cup.runtime.Symbol) CUP$JsonParser$stack.peek()).value;
		RESULT = new Value(sleft, sright, s + v, Type.DOUBLE);
              CUP$JsonParser$result = parser.getSymbolFactory().newSymbol("ValueType",4, ((java_cup.runtime.Symbol)CUP$JsonParser$stack.elementAt(CUP$JsonParser$top-1)), ((java_cup.runtime.Symbol)CUP$JsonParser$stack.peek()), RESULT);
            }
          return CUP$JsonParser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$JsonParser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$JsonParser$do_action(
    int                        CUP$JsonParser$act_num,
    java_cup.runtime.lr_parser CUP$JsonParser$parser,
    java.util.Stack            CUP$JsonParser$stack,
    int                        CUP$JsonParser$top)
    throws java.lang.Exception
    {
              return CUP$JsonParser$do_action_part00000000(
                               CUP$JsonParser$act_num,
                               CUP$JsonParser$parser,
                               CUP$JsonParser$stack,
                               CUP$JsonParser$top);
    }
}

}
