
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package gt.edu.usac.ingenieria.analyzer.json;

/** CUP generated interface containing symbol constants. */
public interface SYM {
  /* terminals */
  public static final int TK_DOUBLE = 8;
  public static final int TK_LBRC = 2;
  public static final int TK_COMA = 5;
  public static final int EOF = 0;
  public static final int TK_INT = 7;
  public static final int error = 1;
  public static final int TK_RBRC = 3;
  public static final int TK_MINUS = 9;
  public static final int TK_STRING = 6;
  public static final int TK_COLON = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TK_LBRC",
  "TK_RBRC",
  "TK_COLON",
  "TK_COMA",
  "TK_STRING",
  "TK_INT",
  "TK_DOUBLE",
  "TK_MINUS"
  };
}

