/* The following code was generated by JFlex 1.7.0 */

// package and imports
package gt.edu.usac.ingenieria.analyzer;
import java_cup.runtime.Symbol;
import java.util.ArrayList;
import gt.edu.usac.ingenieria.analyzer.errors.ErrorStpL;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>src/main/java/gt/edu/usac/ingenieria/analyzer/StatPy.jflex</tt>
 */
public class StatPyLexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  4,  6,  6,  5,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     1, 42,  2,  0,  0,  0, 43, 10, 45, 46, 13, 37, 51, 38, 11, 12, 
     9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  0, 52, 41, 40, 39,  0, 
     0, 20, 24, 27, 18, 26, 33, 32, 28, 17,  8, 36, 25, 19, 21, 15, 
     8,  8, 29, 31, 22, 23, 14, 34,  8,  8,  8, 49,  3, 50,  0,  7, 
     0, 20, 24, 27, 18, 26, 33, 32, 28, 17,  8, 36, 25, 19, 21, 15, 
     8,  8, 29, 31, 22, 23, 14, 34,  8,  8,  8, 47, 44, 48,  0,  0, 
     0,  0,  0,  0,  0,  6,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\1\1\3\1\1\1\4\1\5"+
    "\1\1\1\6\1\7\1\4\1\1\7\4\1\1\3\4"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\2\1\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\0"+
    "\1\26\5\0\1\2\1\0\1\4\1\0\1\27\1\4"+
    "\1\27\1\30\11\4\2\0\4\4\1\31\1\32\1\33"+
    "\1\34\1\35\1\36\1\37\1\40\2\0\1\4\2\41"+
    "\2\4\1\0\3\4\1\0\2\4\1\0\3\4\2\0"+
    "\2\4\1\42\1\0\1\4\1\2\2\43\2\4\2\44"+
    "\1\45\1\4\2\46\1\4\2\47\1\50\1\4\2\0"+
    "\2\4\1\0\3\4\2\51\1\0\2\4\2\0\2\4"+
    "\2\52\1\53\1\4\1\0\1\4\1\54\1\55\1\56"+
    "\1\55\1\56\1\57\1\0\1\4\2\60";

  private static int [] zzUnpackAction() {
    int [] result = new int[152];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\65\0\152\0\237\0\65\0\324\0\u0109\0\u013e"+
    "\0\u0173\0\u01a8\0\65\0\u01dd\0\u0212\0\u0247\0\u027c\0\u02b1"+
    "\0\u02e6\0\u031b\0\u0350\0\u0385\0\u03ba\0\u03ef\0\u0424\0\u0459"+
    "\0\65\0\65\0\u048e\0\u04c3\0\u04f8\0\u052d\0\u0562\0\u0597"+
    "\0\65\0\65\0\65\0\65\0\65\0\65\0\65\0\65"+
    "\0\237\0\65\0\u05cc\0\324\0\u0601\0\u0636\0\u066b\0\u06a0"+
    "\0\u06d5\0\u070a\0\u073f\0\65\0\u0774\0\u0109\0\u07a9\0\u07de"+
    "\0\u0813\0\u0848\0\u087d\0\u08b2\0\u08e7\0\u091c\0\u0951\0\u0986"+
    "\0\u09bb\0\u09f0\0\u0a25\0\u0a5a\0\u0a8f\0\u0ac4\0\65\0\65"+
    "\0\65\0\65\0\65\0\65\0\u0601\0\65\0\u0af9\0\u0b2e"+
    "\0\u0b63\0\65\0\u0109\0\u0b98\0\u0bcd\0\u0c02\0\u0c37\0\u0c6c"+
    "\0\u0ca1\0\u0cd6\0\u0d0b\0\u0d40\0\u0d75\0\u0daa\0\u0ddf\0\u0e14"+
    "\0\u0e49\0\u0e7e\0\u0eb3\0\u0ee8\0\u0109\0\u0f1d\0\u0f52\0\65"+
    "\0\65\0\u0109\0\u0f87\0\u0fbc\0\65\0\u0109\0\u0109\0\u0ff1"+
    "\0\65\0\u0109\0\u1026\0\65\0\u0109\0\u0109\0\u105b\0\u1090"+
    "\0\u10c5\0\u10fa\0\u112f\0\u1164\0\u1199\0\u11ce\0\u1203\0\65"+
    "\0\u0109\0\u1238\0\u126d\0\u12a2\0\u12d7\0\u130c\0\u1341\0\u1376"+
    "\0\65\0\u0109\0\u0109\0\u13ab\0\u13e0\0\u1415\0\u0109\0\65"+
    "\0\65\0\u0109\0\u0109\0\u0109\0\u144a\0\u147f\0\65\0\u0109";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[152];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\2\1\5\1\3\1\0\1\6"+
    "\1\7\1\10\1\11\1\2\1\12\1\13\1\14\1\7"+
    "\1\15\1\16\1\17\1\20\4\7\1\21\1\7\1\22"+
    "\1\23\1\7\1\24\1\25\1\26\1\7\1\27\1\30"+
    "\1\2\1\7\1\31\1\32\1\33\1\34\1\35\1\36"+
    "\1\37\1\40\1\41\1\42\1\43\1\44\1\45\1\46"+
    "\1\47\1\50\66\0\1\3\3\0\1\3\57\0\2\51"+
    "\1\52\1\53\1\0\60\51\7\0\1\54\1\7\5\0"+
    "\2\7\1\0\15\7\1\0\4\7\1\0\1\7\27\0"+
    "\3\7\4\0\2\7\1\0\15\7\1\0\4\7\1\0"+
    "\1\7\31\0\1\10\1\0\1\55\51\0\2\56\1\0"+
    "\1\57\1\0\60\56\14\0\1\60\1\61\56\0\3\7"+
    "\4\0\1\7\1\62\1\0\15\7\1\0\4\7\1\0"+
    "\1\7\45\0\1\63\13\0\1\64\32\0\3\7\4\0"+
    "\2\7\1\0\4\7\1\65\10\7\1\0\2\7\1\66"+
    "\1\7\1\0\1\7\27\0\3\7\4\0\1\7\1\67"+
    "\1\0\11\7\1\70\3\7\1\0\4\7\1\0\1\7"+
    "\27\0\3\7\4\0\2\7\1\0\3\7\1\71\11\7"+
    "\1\0\4\7\1\0\1\7\27\0\3\7\4\0\1\7"+
    "\1\72\1\0\14\7\1\73\1\0\4\7\1\0\1\7"+
    "\27\0\3\7\4\0\2\7\1\0\10\7\1\74\4\7"+
    "\1\0\4\7\1\0\1\7\27\0\3\7\4\0\1\7"+
    "\1\75\1\0\3\7\1\76\7\7\1\77\1\7\1\0"+
    "\4\7\1\0\1\7\27\0\3\7\4\0\2\7\1\0"+
    "\11\7\1\100\3\7\1\0\4\7\1\0\1\7\46\0"+
    "\1\101\13\0\1\102\31\0\3\7\4\0\2\7\1\0"+
    "\5\7\1\103\7\7\1\0\3\7\1\104\1\0\1\7"+
    "\27\0\3\7\4\0\1\7\1\105\1\0\15\7\1\0"+
    "\4\7\1\0\1\7\27\0\3\7\4\0\2\7\1\0"+
    "\13\7\1\106\1\7\1\0\4\7\1\0\1\7\70\0"+
    "\1\107\64\0\1\110\64\0\1\111\64\0\1\112\67\0"+
    "\1\113\65\0\1\114\10\0\4\51\3\0\56\51\11\0"+
    "\1\115\65\0\1\116\52\0\4\56\3\0\56\56\4\60"+
    "\2\0\57\60\15\61\1\117\47\61\7\0\3\7\4\0"+
    "\2\7\1\120\1\121\14\7\1\0\4\7\1\0\1\7"+
    "\46\0\1\122\45\0\3\7\4\0\2\7\1\0\5\7"+
    "\1\123\7\7\1\0\4\7\1\0\1\7\27\0\3\7"+
    "\4\0\2\7\1\0\6\7\1\124\6\7\1\0\4\7"+
    "\1\0\1\7\27\0\3\7\4\0\2\7\1\0\15\7"+
    "\1\0\2\7\1\125\1\7\1\0\1\7\27\0\3\7"+
    "\4\0\2\7\1\126\1\127\14\7\1\0\4\7\1\0"+
    "\1\7\27\0\3\7\4\0\1\7\1\130\1\0\15\7"+
    "\1\0\4\7\1\0\1\7\27\0\3\7\4\0\2\7"+
    "\1\0\11\7\1\131\3\7\1\0\4\7\1\0\1\7"+
    "\27\0\3\7\4\0\2\7\1\0\15\7\1\132\1\133"+
    "\3\7\1\0\1\7\27\0\3\7\4\0\2\7\1\0"+
    "\4\7\1\134\10\7\1\0\4\7\1\0\1\7\27\0"+
    "\3\7\4\0\2\7\1\0\15\7\1\135\1\136\3\7"+
    "\1\0\1\7\27\0\3\7\4\0\2\7\1\0\3\7"+
    "\1\137\11\7\1\0\4\7\1\0\1\7\27\0\3\7"+
    "\4\0\2\7\1\0\5\7\1\140\7\7\1\0\4\7"+
    "\1\0\1\7\55\0\1\141\47\0\2\142\52\0\3\7"+
    "\4\0\2\7\1\0\14\7\1\143\1\0\4\7\1\0"+
    "\1\7\27\0\3\7\4\0\2\7\1\142\1\144\14\7"+
    "\1\0\4\7\1\0\1\7\27\0\3\7\4\0\2\7"+
    "\1\0\14\7\1\145\1\0\4\7\1\0\1\7\27\0"+
    "\3\7\4\0\2\7\1\146\1\147\14\7\1\0\4\7"+
    "\1\0\1\7\20\0\14\61\1\150\1\117\47\61\22\0"+
    "\1\151\51\0\3\7\4\0\2\7\1\0\1\7\1\152"+
    "\13\7\1\0\4\7\1\0\1\7\27\0\3\7\4\0"+
    "\2\7\1\0\7\7\1\153\5\7\1\0\4\7\1\0"+
    "\1\7\27\0\3\7\4\0\2\7\1\0\3\7\1\154"+
    "\11\7\1\0\4\7\1\0\1\7\45\0\1\155\46\0"+
    "\3\7\4\0\2\7\1\0\4\7\1\156\10\7\1\0"+
    "\4\7\1\0\1\7\27\0\3\7\4\0\2\7\1\0"+
    "\10\7\1\157\4\7\1\0\4\7\1\0\1\7\27\0"+
    "\3\7\4\0\2\7\1\0\3\7\1\160\11\7\1\0"+
    "\4\7\1\0\1\7\52\0\1\161\41\0\3\7\4\0"+
    "\2\7\1\0\11\7\1\162\3\7\1\0\4\7\1\0"+
    "\1\7\27\0\3\7\4\0\2\7\1\0\5\7\1\163"+
    "\7\7\1\0\4\7\1\0\1\7\52\0\1\164\41\0"+
    "\3\7\4\0\2\7\1\0\11\7\1\165\3\7\1\0"+
    "\4\7\1\0\1\7\27\0\3\7\4\0\2\7\1\0"+
    "\14\7\1\166\1\0\4\7\1\0\1\7\27\0\3\7"+
    "\4\0\2\7\1\0\6\7\1\167\6\7\1\0\4\7"+
    "\1\0\1\7\40\0\2\170\71\0\1\171\45\0\3\7"+
    "\4\0\2\7\1\170\1\172\14\7\1\0\4\7\1\0"+
    "\1\7\27\0\3\7\4\0\2\7\1\0\5\7\1\173"+
    "\7\7\1\0\4\7\1\0\1\7\51\0\1\174\42\0"+
    "\3\7\4\0\2\7\1\0\10\7\1\175\4\7\1\0"+
    "\4\7\1\0\1\7\27\0\3\7\4\0\2\7\1\0"+
    "\10\7\1\176\4\7\1\0\4\7\1\0\1\7\27\0"+
    "\3\7\4\0\2\7\1\0\6\7\1\177\6\7\1\0"+
    "\4\7\1\0\1\7\27\0\3\7\4\0\2\7\1\0"+
    "\15\7\1\0\4\7\1\200\1\201\27\0\3\7\4\0"+
    "\2\7\1\202\1\203\14\7\1\0\4\7\1\0\1\7"+
    "\27\0\3\7\4\0\2\7\1\0\14\7\1\204\1\0"+
    "\4\7\1\0\1\7\45\0\1\205\72\0\1\206\40\0"+
    "\3\7\4\0\2\7\1\0\4\7\1\207\10\7\1\0"+
    "\4\7\1\0\1\7\27\0\3\7\4\0\2\7\1\0"+
    "\12\7\1\210\2\7\1\0\4\7\1\0\1\7\52\0"+
    "\1\211\41\0\3\7\4\0\2\7\1\0\11\7\1\212"+
    "\3\7\1\0\4\7\1\0\1\7\27\0\3\7\4\0"+
    "\2\7\1\0\11\7\1\213\3\7\1\0\4\7\1\0"+
    "\1\7\27\0\3\7\4\0\2\7\1\0\10\7\1\214"+
    "\4\7\1\0\4\7\1\0\1\7\45\0\1\215\46\0"+
    "\3\7\4\0\2\7\1\0\4\7\1\216\10\7\1\0"+
    "\4\7\1\0\1\7\27\0\3\7\4\0\2\7\1\0"+
    "\4\7\1\217\10\7\1\0\4\7\1\0\1\7\60\0"+
    "\1\220\60\0\1\221\37\0\3\7\4\0\2\7\1\0"+
    "\15\7\1\0\1\7\1\222\2\7\1\0\1\7\27\0"+
    "\3\7\4\0\2\7\1\0\13\7\1\223\1\7\1\0"+
    "\4\7\1\0\1\7\27\0\3\7\4\0\2\7\1\0"+
    "\5\7\1\224\7\7\1\0\4\7\1\0\1\7\47\0"+
    "\1\225\44\0\3\7\4\0\2\7\1\0\6\7\1\226"+
    "\6\7\1\0\4\7\1\0\1\7\52\0\1\227\41\0"+
    "\3\7\4\0\2\7\1\0\11\7\1\230\3\7\1\0"+
    "\4\7\1\0\1\7\20\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5300];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\2\1\1\11\5\1\1\11\15\1\2\11"+
    "\6\1\10\11\1\0\1\11\5\0\1\1\1\0\1\1"+
    "\1\0\1\11\14\1\2\0\4\1\6\11\1\1\1\11"+
    "\2\0\1\1\1\11\3\1\1\0\3\1\1\0\2\1"+
    "\1\0\3\1\2\0\3\1\1\0\1\1\2\11\3\1"+
    "\1\11\3\1\1\11\2\1\1\11\3\1\2\0\2\1"+
    "\1\0\3\1\1\11\1\1\1\0\2\1\2\0\2\1"+
    "\1\11\3\1\1\0\2\1\2\11\3\1\1\0\1\1"+
    "\1\11\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[152];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    private ArrayList<ErrorStpL> errors = new ArrayList<>();
    private void addError(int line, int column, String character){
        errors.add(new ErrorStpL(line, column, character));
    }

    public ArrayList<ErrorStpL> getErrors(){
        return errors;
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public StatPyLexer(java.io.Reader in) {
      yyline = 1;
    yychar = 1;
    this.zzReader = in;
  }



  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(SYM.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { addError(yyline, yychar, yytext());
            } 
            // fall through
          case 49: break;
          case 2: 
            { 
            } 
            // fall through
          case 50: break;
          case 3: 
            { yychar = 1;
            } 
            // fall through
          case 51: break;
          case 4: 
            { return new Symbol(SYM.TK_ID,           yyline, yychar, yytext());
            } 
            // fall through
          case 52: break;
          case 5: 
            { return new Symbol(SYM.TK_INT,          yyline, yychar, yytext());
            } 
            // fall through
          case 53: break;
          case 6: 
            { return new Symbol(SYM.TK_DIV,          yyline, yychar, yytext());
            } 
            // fall through
          case 54: break;
          case 7: 
            { return new Symbol(SYM.TK_MULT,         yyline, yychar, yytext());
            } 
            // fall through
          case 55: break;
          case 8: 
            { return new Symbol(SYM.TK_PLUS,         yyline, yychar, yytext());
            } 
            // fall through
          case 56: break;
          case 9: 
            { return new Symbol(SYM.TK_MINUS,        yyline, yychar, yytext());
            } 
            // fall through
          case 57: break;
          case 10: 
            { return new Symbol(SYM.TK_GREATER,      yyline, yychar, yytext());
            } 
            // fall through
          case 58: break;
          case 11: 
            { return new Symbol(SYM.TK_EQ,           yyline, yychar, yytext());
            } 
            // fall through
          case 59: break;
          case 12: 
            { return new Symbol(SYM.TK_LESS,         yyline, yychar, yytext());
            } 
            // fall through
          case 60: break;
          case 13: 
            { return new Symbol(SYM.TK_NOT,          yyline, yychar, yytext());
            } 
            // fall through
          case 61: break;
          case 14: 
            { return new Sybmol(SYM.TK_LPAR,         yyline, yychar, yytext());
            } 
            // fall through
          case 62: break;
          case 15: 
            { return new Sybmol(SYM.TK_RPAR,         yyline, yychar, yytext());
            } 
            // fall through
          case 63: break;
          case 16: 
            { return new Sybmol(SYM.TK_LBR,          yyline, yychar, yytext());
            } 
            // fall through
          case 64: break;
          case 17: 
            { return new Sybmol(SYM.TK_RBR,          yyline, yychar, yytext());
            } 
            // fall through
          case 65: break;
          case 18: 
            { return new Sybmol(SYM.TK_LBRK,         yyline, yychar, yytext());
            } 
            // fall through
          case 66: break;
          case 19: 
            { return new Sybmol(SYM.TK_RBRK,         yyline, yychar, yytext());
            } 
            // fall through
          case 67: break;
          case 20: 
            { return new Symbol(SYM.TK_COMA          yyline, yychar, yytext());
            } 
            // fall through
          case 68: break;
          case 21: 
            { return new Symbol(SYM.TK_SCOLON        yyline, yychar, yytext());
            } 
            // fall through
          case 69: break;
          case 22: 
            { return new Symbol(SYM.TK_STRING,       yyline, yychar, yytext());
            } 
            // fall through
          case 70: break;
          case 23: 
            { return new Symbol(SYM.KW_IF,           yyline, yychar, yytext());
            } 
            // fall through
          case 71: break;
          case 24: 
            { return new Symbol(SYM.KW_DO,           yyline, yychar, yytext());
            } 
            // fall through
          case 72: break;
          case 25: 
            { return new Symbol(SYM.TK_GEQ,          yyline, yychar, yytext());
            } 
            // fall through
          case 73: break;
          case 26: 
            { return new Symbol(SYM.TK_EQEQ,         yyline, yychar, yytext());
            } 
            // fall through
          case 74: break;
          case 27: 
            { return new Symbol(SYM.TK_LEQ,          yyline, yychar, yytext());
            } 
            // fall through
          case 75: break;
          case 28: 
            { return new Symbol(SYM.TK_NEQ,          yyline, yychar, yytext());
            } 
            // fall through
          case 76: break;
          case 29: 
            { return new Symbol(SYM.TK_AND,          yyline, yychar, yytext());
            } 
            // fall through
          case 77: break;
          case 30: 
            { return new Symbol(SYM.TK_OR,           yyline, yychar, yytext());
            } 
            // fall through
          case 78: break;
          case 31: 
            { return new Symbol(SYM.TK_DOUBLE,       yyline, yychar, yytext());
            } 
            // fall through
          case 79: break;
          case 32: 
            { return new Symbol(SYM.TK_CHAR,         yyline, yychar, yytext());
            } 
            // fall through
          case 80: break;
          case 33: 
            { return new Symbol(SYM.KW_INT,          yyline, yychar, yytext());
            } 
            // fall through
          case 81: break;
          case 34: 
            { return new Symbol(SYM.KW_FOR,          yyline, yychar, yytext());
            } 
            // fall through
          case 82: break;
          case 35: 
            { return new Symbol(SYM.KW_VOID,         yyline, yychar, yytext());
            } 
            // fall through
          case 83: break;
          case 36: 
            { return new Symbol(SYM.KW_MAIN,         yyline, yychar, yytext());
            } 
            // fall through
          case 84: break;
          case 37: 
            { return new Symbol(SYM.KW_BOOL,         yyline, yychar, yytext());
            } 
            // fall through
          case 85: break;
          case 38: 
            { return new Symbol(SYM.KW_ELSE,         yyline, yychar, yytext());
            } 
            // fall through
          case 86: break;
          case 39: 
            { return new Symbol(SYM.KW_CASE,         yyline, yychar, yytext());
            } 
            // fall through
          case 87: break;
          case 40: 
            { return new Symbol(SYM.KW_CHAR,         yyline, yychar, yytext());
            } 
            // fall through
          case 88: break;
          case 41: 
            { return new Symbol(SYM.KW_BREAK,        yyline, yychar, yytext());
            } 
            // fall through
          case 89: break;
          case 42: 
            { return new Symbol(SYM.KW_WHILE,        yyline, yychar, yytext());
            } 
            // fall through
          case 90: break;
          case 43: 
            { return new Symbol(SYM.KW_DOUBLE,       yyline, yychar, yytext());
            } 
            // fall through
          case 91: break;
          case 44: 
            { return new Symbol(SYM.KW_RETURN,       yyline, yychar, yytext());
            } 
            // fall through
          case 92: break;
          case 45: 
            { return new Symbol(SYM.KW_STRING,       yyline, yychar, yytext());
            } 
            // fall through
          case 93: break;
          case 46: 
            { return new Symbol(SYM.KW_SWITCH,       yyline, yychar, yytext());
            } 
            // fall through
          case 94: break;
          case 47: 
            { return new Symbol(SYM.KW_DEFAULT,      yyline, yychar, yytext());
            } 
            // fall through
          case 95: break;
          case 48: 
            { return new Symbol(SYM.KW_CONTINUE,     yyline, yychar, yytext());
            } 
            // fall through
          case 96: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
