
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package gt.edu.usac.ingenieria.analyzer.statpy;

/** CUP generated interface containing symbol constants. */
public interface SYM {
  /* terminals */
  public static final int TK_UMINUS = 38;
  public static final int TK_GREATER = 33;
  public static final int TK_MINUS = 26;
  public static final int TK_INT = 22;
  public static final int TK_DOUBLE = 23;
  public static final int KW_INT = 4;
  public static final int TK_NOT = 37;
  public static final int TK_AND = 35;
  public static final int TK_OR = 36;
  public static final int KW_FOR = 15;
  public static final int TK_LESS = 34;
  public static final int KW_DO = 16;
  public static final int KW_DOUBLE = 5;
  public static final int KW_CHAR = 6;
  public static final int TK_RPAR = 40;
  public static final int TK_DIV = 28;
  public static final int TK_GEQ = 29;
  public static final int TK_ID = 24;
  public static final int KW_CASE = 12;
  public static final int TK_PLUS = 25;
  public static final int TK_RBRK = 44;
  public static final int TK_SCOLON = 47;
  public static final int TK_EQ = 45;
  public static final int TK_COMA = 46;
  public static final int TK_RBRC = 42;
  public static final int KW_BOOL = 7;
  public static final int KW_CONTINUE = 18;
  public static final int KW_RETURN = 19;
  public static final int TK_EQEQ = 31;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int KW_MAIN = 2;
  public static final int KW_SWITCH = 11;
  public static final int KW_IF = 9;
  public static final int TK_LEQ = 30;
  public static final int KW_VOID = 3;
  public static final int KW_BREAK = 14;
  public static final int TK_STRING = 20;
  public static final int TK_LPAR = 39;
  public static final int TK_NOTEQ = 32;
  public static final int KW_ELSE = 10;
  public static final int KW_STRING = 8;
  public static final int KW_DEFAULT = 13;
  public static final int KW_WHILE = 17;
  public static final int TK_LBRK = 43;
  public static final int TK_MULT = 27;
  public static final int TK_LBRC = 41;
  public static final int TK_CHAR = 21;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "KW_MAIN",
  "KW_VOID",
  "KW_INT",
  "KW_DOUBLE",
  "KW_CHAR",
  "KW_BOOL",
  "KW_STRING",
  "KW_IF",
  "KW_ELSE",
  "KW_SWITCH",
  "KW_CASE",
  "KW_DEFAULT",
  "KW_BREAK",
  "KW_FOR",
  "KW_DO",
  "KW_WHILE",
  "KW_CONTINUE",
  "KW_RETURN",
  "TK_STRING",
  "TK_CHAR",
  "TK_INT",
  "TK_DOUBLE",
  "TK_ID",
  "TK_PLUS",
  "TK_MINUS",
  "TK_MULT",
  "TK_DIV",
  "TK_GEQ",
  "TK_LEQ",
  "TK_EQEQ",
  "TK_NOTEQ",
  "TK_GREATER",
  "TK_LESS",
  "TK_AND",
  "TK_OR",
  "TK_NOT",
  "TK_UMINUS",
  "TK_LPAR",
  "TK_RPAR",
  "TK_LBRC",
  "TK_RBRC",
  "TK_LBRK",
  "TK_RBRK",
  "TK_EQ",
  "TK_COMA",
  "TK_SCOLON"
  };
}

