
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package gt.edu.usac.ingenieria.analyzer.statpy;

/** CUP generated interface containing symbol constants. */
public interface SYM {
  /* terminals */
  public static final int TK_UMINUS = 50;
  public static final int TK_GREATER = 45;
  public static final int TK_MINUS = 38;
  public static final int TK_INT = 32;
  public static final int KW_FALSE = 21;
  public static final int TK_DOLL = 61;
  public static final int TK_DOUBLE = 33;
  public static final int KW_INT = 4;
  public static final int TK_NOT = 49;
  public static final int TK_AND = 47;
  public static final int KW_BARGRPH = 23;
  public static final int TK_OR = 48;
  public static final int TK_LESS = 46;
  public static final int KW_FOR = 15;
  public static final int KW_DO = 16;
  public static final int KW_DOUBLE = 5;
  public static final int KW_CHAR = 6;
  public static final int TK_INC = 35;
  public static final int KW_DEFGLB = 22;
  public static final int TK_RPAR = 52;
  public static final int TK_DIV = 40;
  public static final int TK_GEQ = 41;
  public static final int TK_ID = 34;
  public static final int KW_CASE = 12;
  public static final int TK_PLUS = 37;
  public static final int TK_RBRK = 56;
  public static final int TK_SCOLON = 59;
  public static final int TK_EQ = 57;
  public static final int TK_COMA = 58;
  public static final int TK_RBRC = 54;
  public static final int KW_BOOL = 7;
  public static final int KW_CONTINUE = 18;
  public static final int TK_COLON = 60;
  public static final int TK_EQEQ = 43;
  public static final int KW_RETURN = 19;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int KW_MAIN = 2;
  public static final int KW_VALUES = 27;
  public static final int KW_TITLEY = 29;
  public static final int KW_TITLEX = 28;
  public static final int KW_TRUE = 20;
  public static final int KW_SWITCH = 11;
  public static final int KW_IF = 9;
  public static final int TK_LEQ = 42;
  public static final int KW_VOID = 3;
  public static final int TK_DEC = 36;
  public static final int KW_BREAK = 14;
  public static final int TK_STRING = 30;
  public static final int TK_LPAR = 51;
  public static final int TK_NOTEQ = 44;
  public static final int KW_ELSE = 10;
  public static final int KW_STRING = 8;
  public static final int KW_XAXIS = 26;
  public static final int KW_TITLE = 25;
  public static final int KW_PIEGRPH = 24;
  public static final int KW_DEFAULT = 13;
  public static final int KW_WHILE = 17;
  public static final int TK_LBRK = 55;
  public static final int TK_MULT = 39;
  public static final int TK_LBRC = 53;
  public static final int TK_CHAR = 31;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "KW_MAIN",
  "KW_VOID",
  "KW_INT",
  "KW_DOUBLE",
  "KW_CHAR",
  "KW_BOOL",
  "KW_STRING",
  "KW_IF",
  "KW_ELSE",
  "KW_SWITCH",
  "KW_CASE",
  "KW_DEFAULT",
  "KW_BREAK",
  "KW_FOR",
  "KW_DO",
  "KW_WHILE",
  "KW_CONTINUE",
  "KW_RETURN",
  "KW_TRUE",
  "KW_FALSE",
  "KW_DEFGLB",
  "KW_BARGRPH",
  "KW_PIEGRPH",
  "KW_TITLE",
  "KW_XAXIS",
  "KW_VALUES",
  "KW_TITLEX",
  "KW_TITLEY",
  "TK_STRING",
  "TK_CHAR",
  "TK_INT",
  "TK_DOUBLE",
  "TK_ID",
  "TK_INC",
  "TK_DEC",
  "TK_PLUS",
  "TK_MINUS",
  "TK_MULT",
  "TK_DIV",
  "TK_GEQ",
  "TK_LEQ",
  "TK_EQEQ",
  "TK_NOTEQ",
  "TK_GREATER",
  "TK_LESS",
  "TK_AND",
  "TK_OR",
  "TK_NOT",
  "TK_UMINUS",
  "TK_LPAR",
  "TK_RPAR",
  "TK_LBRC",
  "TK_RBRC",
  "TK_LBRK",
  "TK_RBRK",
  "TK_EQ",
  "TK_COMA",
  "TK_SCOLON",
  "TK_COLON",
  "TK_DOLL"
  };
}

